=== 暖房時における運転方法について

==== 1. 概要

　省エネ基準では、暖房時の運転方法は、選択された設備機器の種類によって、「住戸全体を連続的に暖房」「居室を連続的に暖房」「居室を間歇的に暖房」が設定される。

　自立循環プログラムの場合は、

- 省エネ基準と同じように運転方法を想定するモード
- 運転方法を「連続運転」と「間歇運転」から選択できるモード

を用意する。ただし、居室暖房のみである（ダクト式セントラル空調は除く）。

==== 2. 変更箇所

第4章「暖冷房設備」第1節「全般」付録A「設置する暖房設備機器又は放熱器の種類に応じた暖房方式及び運転方法の決定方法並びに評価上想定される暖房設備機器又は放熱器の種類」A.1「設置する暖房設備機器又は放熱器の種類に応じた暖房方式及び運転方法の決定方法」

|=================================
|　当該住戸に1以上のダクト式セントラル空調機を導入する場合の運転方法は「住戸全体を連続的に暖房する方式」とし、ダクト式セントラル空調機により暖房設備のエネルギー消費量を計算することとする。 +
　上記に該当しない場合の運転方法は「居室のみを暖房する方式」とする。 +
　「居室のみを暖房する方式」の場合の主たる居室及びその他の居室における運転方法は表A.1(a)または(b)による。

表A.1(a) 主たる居室及びその他の居室の運転方法（その他の居室がある場合） +
（上段：主たる居室の運転方法 下段：その他の居室の運転方法）

（表略）

表A.1(b) 主たる居室の運転方法（その他の居室がない場合）

（表略）

|=================================

==== 3. 変更内容

　当該住戸に1以上のダクト式セントラル空調機を導入する場合の運転方法は「住戸全体を連続的に暖房する方式」とし、ダクト式セントラル空調機により暖房設備のエネルギー消費量を計算することとする。（省エネ基準からの修正なし） +
　上記に該当しない場合の運転方法は「居室のみを暖房する方式」とする。（省エネ基準からの修正なし） +
　「居室のみを暖房する方式」の場合の主たる居室及びその他の居室における運転方法は、

- 「指定する」
- 「指定しない」

に分かれ、「指定する」の場合は、主たる居室・その他の居室それぞれにおいて「連続運転」「間歇運転」を選択できるようにする。 +
「指定しない」場合は、省エネ基準同様、表A.1(a)及び表A.1(b)に示されるように設置される機器に応じて運転方法が定まることとする。

==== 4. 備考

- 住戸全体を連続的に暖房する場合（ダクト式セントラル空調が該当）の場合も将来的には連続運転・間歇運転が選択できるようになることは望ましい。省エネ基準において、現在、住戸全体を連続的に暖房するという概念から、「居室を連続的に暖房しかつ居室から非居室へ流れる循環風量が多い方式」、その結果として住戸全体がなんとなく暖房されているような方式に修正中である。その修正が終了すると、循環風量を維持したまま居室の連続・間歇が選択できるようになるため、一連の修正を終えてから取り組むことにする。
- 冷房時の運転方法については、（AE&SOlによる試算は終了したものの、その整理が終わってはおらず）連続冷房の負荷が存在しないため、現在省エネ基準で実施している簡易負荷計算の導入を待ってから、検討を開始することとする。（簡易負荷計算を実装すると、動的に冷房負荷計算が可能となる。）
