=== 家電について

==== 1. 概要

省エネ基準では1人～4人の家電消費量が、家電スケジュール「平日」「休日外出」「休日在宅」に応じて1時間ごとに決まっており、仮想居住人数（1人～4人の間の値をとる）に応じて時々刻々按分している。

自立循環プログラムでは、仮想居住人数に応じて時々刻々按分する部分は同じとし、1時間ごとに決まっている家電スケジュールに応じて決まっている家電消費量の算出方法を、値で与えるのではなく、個々の家電機器を想定して計算できるようにする。
なお、個々に算出した家電機器の消費電力を合計した値と、省エネ基準で用いられている値とは、微妙にずれるため、上位互換を維持するために、インターフェース上では、「個々の家電機器を計算する方法」と「省エネ基準で定められた値を使用する方法」の2種類用意する。

==== 2. 変更内容

省エネ基準では1人～4人の家電消費量が、家電スケジュール「平日」「休日外出」「休日在宅」に応じて1時間ごとに決まっており、仮想居住人数（1人～4人の間の値をとる）に応じて時々刻々按分している。

自立循環プログラムでは、仮想居住人数に応じて時々刻々按分する部分は同じとし、1時間ごとに決まっている家電スケジュールに応じて決まっている家電消費量の算出方法を、値で与えるのではなく、個々の家電機器を想定して計算できるようにする。
なお、個々に算出した家電機器の消費電力を合計した値と、省エネ基準で用いられている値とは、微妙にずれるため、上位互換を維持するために、インターフェース上では、「個々の家電機器を計算する方法」と「省エネ基準で定められた値を使用する方法」の2種類用意する。


==== 3. 変更内容

省エネ基準では1人～4人の家電消費量が、家電スケジュール「平日」「休日外出」「休日在宅」に応じて1時間ごとに決まっており、仮想居住人数（1人～4人の間の値をとる）に応じて時々刻々按分している。

自立循環プログラムでは、仮想居住人数に応じて時々刻々按分する部分は同じとし、1時間ごとに決まっている家電スケジュールに応じて決まっている家電消費量の算出方法を、値で与えるのではなく、個々の家電機器を想定して計算できるようにする。
なお、個々に算出した家電機器の消費電力を合計した値と、省エネ基準で用いられている値とは、微妙にずれるため、上位互換を維持するために、インターフェース上では、「個々の家電機器を計算する方法」と「省エネ基準で定められた値を使用する方法」の2種類用意する。


==== 3.1． 家電


==== 3.2. 冷蔵庫


1日単位の消費電力
E_d,t=　　｛150 * 0.9 * 1　|t=0,23
　　　　　｛E_operate,d 　|t<>0,23


E_operate,d =[(3.283×10^(-3)-2.0×10^(-6)×E_(E,ref,annual_rtd_1999,a) )×(θ_(amb,ave,d)^2-30×θ_(amb,ave,d) )+1.85×10^(-3)×E_(E,ref,annual_rtd_1999,a)+1.329]×1000


θ_(amb,ave,d)=0.4142×θ_(o,ave,d)+15.47



製造年が2005年以前（JIS C 9801:1999による）：
E_ref,annual_rtd = habara formula 

製造年が2006年～2015年（JIS C 9801:2006による）：
E_ref,annual_rtd = habara formula

製造年が2016年以降（JIS C 9801:2015による）：
E_ref,annual_rtd = habara formula




==== 3.2． 家電

hogehoge



