:stem: latexmath

=== 家電について

==== 1. 概要

省エネ基準では1人～4人の家電消費量が、家電スケジュール「平日」「休日外出」「休日在宅」に応じて1時間ごとに決まっており、仮想居住人数（1人～4人の間の値をとる）に応じて時々刻々按分している。

自立循環プログラムでは、仮想居住人数に応じて時々刻々按分する部分は同じとし、1時間ごとに決まっている家電スケジュールに応じて決まっている家電消費量の算出方法を、値で与えるのではなく、個々の家電機器を想定して計算できるようにする。
なお、個々に算出した家電機器の消費電力を合計した値と、省エネ基準で用いられている値とは、微妙にずれるため、上位互換を維持するために、インターフェース上では、「個々の家電機器を計算する方法」と「省エネ基準で定められた値を使用する方法」の2種類用意する。

==== 2. 変更内容

省エネ基準では1人～4人の家電消費量が、家電スケジュール「平日」「休日外出」「休日在宅」に応じて1時間ごとに決まっており、仮想居住人数（1人～4人の間の値をとる）に応じて時々刻々按分している。

自立循環プログラムでは、仮想居住人数に応じて時々刻々按分する部分は同じとし、1時間ごとに決まっている家電スケジュールに応じて決まっている家電消費量の算出方法を、値で与えるのではなく、個々の家電機器を想定して計算できるようにする。
なお、個々に算出した家電機器の消費電力を合計した値と、省エネ基準で用いられている値とは、微妙にずれるため、上位互換を維持するために、インターフェース上では、「個々の家電機器を計算する方法」と「省エネ基準で定められた値を使用する方法」の2種類用意する。


==== 3. 変更内容

省エネ基準では1人～4人の家電消費量が、家電スケジュール「平日」「休日外出」「休日在宅」に応じて1時間ごとに決まっており、仮想居住人数（1人～4人の間の値をとる）に応じて時々刻々按分している。

自立循環プログラムでは、仮想居住人数に応じて時々刻々按分する部分は同じとし、1時間ごとに決まっている家電スケジュールに応じて決まっている家電消費量の算出方法を、値で与えるのではなく、個々の家電機器を想定して計算できるようにする。
なお、個々に算出した家電機器の消費電力を合計した値と、省エネ基準で用いられている値とは、微妙にずれるため、上位互換を維持するために、インターフェース上では、「個々の家電機器を計算する方法」と「省エネ基準で定められた値を使用する方法」の2種類用意する。


==== 3.1． 家電


==== 3.2. 冷蔵庫


===== 3.2.1. 年間消費電力量

////
年間消費電力量は不要だと思われるが、
一応書式として作成する
////

[stem]
++++
E_{ Elc, rfrg } = \sum_{ d = 1 }^{ 365 } E_{ Elc, rfrg, d }
++++

stem:[ E_{ E, rfrg } ] : 冷蔵庫の年間消費電力量[kWh/年] +
stem:[ E_{ E, rfrg, d } ] : stem:[ d ] 日の冷蔵庫の消費電力量[kWh/日] +



===== 3.2.2. 日別消費電力量

////
日別消費電力量は不要だと思われるが、
一応書式として作成する
////


[stem]
// 時刻の開始数値は「0」 or [1]???
++++
E_{ Elc, rfrg, d } = \sum_{ t = 0 }^{ 23 } E_{ Elc, rfrg, d, t }
++++


stem:[ E_{ Elc, rfrg, d, t } ] : stem:[ d ] 日　stem:[ t ] 時の冷蔵庫の消費電力量[kWh/時] +


===== 3.2.3. 時刻別消費電力量

冷蔵庫の動作は「稼働」および「除霜」とする。

稼働は「冷却運転」および「休止状態」を想定し、除霜が行われていない時間は、常にこの状態であるとする。

除霜が行われる時間帯は0時および23時の計2時間とする。
除霜用電熱装置の定格消費電力は 150 W とする。

[stem]
++++
E_{ Elc, rfrg, d, t } = 
\begin
{cases}
P_{ Elc, dfrst, rtd } \times C_{ dfrst, sfty } \times 1     (t = 0, 23) \\
E_{ Elc, rfrg, oprt, d }             (t <> 0, 23)
\end
{cases}
++++


stem:[ E_{ Elc, rfrg, d, t } ] : stem:[d] 日 stem:[t] 時の冷蔵庫の消費電力量[Wh] +
stem:[ P_{ Elc, dfrst, rtd } ] : 冷蔵庫の除霜用電熱装置の定格消費電力( = 150 )[W] +
stem:[ C_{ dfrst, sfty } ] : 冷蔵庫の除霜用電熱装置の消費電力を安全側に評価するための係数( = 0.9 )[-] +
1 : 1時間[h] (消費電力を消費電力量に換算するための数値) +
stem:[ E_{ Elc, rfrg, oprt, d } ] : 冷蔵庫の稼働時における日平均消費電力量[Wh] +


===== 3.2.2. 稼働時の日平均消費電力量

[stem]
++++
E_{ Elc, rfrg, oprt, d } = 
\frac
{ E_{ Elc, rfrg, est, d } }
{ t_{ rfrg, oprt } } 
++++

[stem]
++++
E_{ Elc, rfrg, est, d } = 
[
(3.283 \times 10^{ -3 } - 2.0 \times 10^{ -6 } \times E_{ Elc, rfrg, annual } ) 
\times ( \theta_{ amb, ave, d}^2 - 30 \times \theta_{ amb, ave, d } )
+ 1.85 \times 10^{ -3 } \times E_{ Elc, rfrg, annual}
+ 1.329
]
\times 10^3
++++

stem:[ E_{ Elc, rfrg, oprt, d } ] : stem:[d] 日の冷蔵庫の稼働時平均消費電力量[Wh/時] +
stem:[ E_{ Elc, rfrg, est, d } ] : stem:[d] 日の冷蔵庫の推定消費電力量[kWh/日] +
stem:[ t_{ rfrg, oprt } ] : 冷蔵庫の稼働時間数( = 22 )[時間] +
stem:[ E_{ Elc, rfrg, annual } ] : 冷蔵庫の年間消費電力量[kWh/年] +
stem:[ \theta_{ amb, ave, d } ] : 冷蔵庫の日平均雰囲気温度[℃] +



===== 3.2.3. 冷蔵庫周辺の雰囲気温度

冷蔵庫の日平均雰囲気温度は、建築研究所実証実験棟101号室における日平均冷蔵庫雰囲気温度と日平均外気温度の実測値の回帰式により求める。

[stem]
++++
\theta_{ amb, ave, d } = 
0.4142 \times \theta_{ oa, ave, d } + 15.47
++++

stem:[ \theta_{ oa, ave, d } ] : 日平均外気温度[℃] +



===== 3.2.3. 冷蔵庫の年間消費電力量

冷蔵庫の年間消費電力量は、製品の性能を試験した際のJIS規格の年数により求め方が異なる。

製造年が2005年以前（JIS C 9801:1999による）：

[stem]
++++
E_{ Elc, rfrg, anuual } = APF_{ JIS1999 } 
++++

製造年が2006年～2015年（JIS C 9801:2006による）：

[stem]
++++
E_{ Elc, rfrg, anuual } = \frac{ APF_{ JIS2006 } }{ 3.48 } 
++++

製造年が2016年以降（JIS C 9801:2015による）：

[stem]
++++
E_{ Elc, rfrg, anuual } = \frac{ APF_{ JIS2015 } }{ 3.48 } \times 0.2891
++++

stem:[ E_{ Elc, rfrg, annual } ] : 冷蔵庫の年間消費電力量[kWh/年] +
stem:[ APF_{ JIS1999 } ] : JIS C 9801 1999に基づく冷蔵庫の年間消費電力量[kWh/年] +
stem:[ APF_{ JIS2006 } ] : JIS C 9801 2006に基づく冷蔵庫の年間消費電力量[kWh/年] +
stem:[ APF_{ JIS2015 } ] : JIS C 9801 2015に基づく冷蔵庫の年間消費電力量[kWh/年] +

==== 3.2． 家電2

hogehoge


