:stem: latexmath

=== 全般換気設備の比消費電力について

==== 1. 概要

省エネ基準では全般換気設備の比消費電力量は、日付と時刻に依らず一定の値が設定される。

自立循環プログラムでは、

- 換気方式と日付d時刻tに応じて値を変更可能なモード

を用意する。

==== 2. 変更箇所

第五章「換気設備」第6節「全般換気の消費電力量」第4項「比消費電力」

====
日付dの時刻tにおける比消費電力 stem:[ f_{SFP, d, t} ] は、日付dの時刻tに依らず同じ値 stem:[ f_{SFP} ] に等しいとし、全般換気設備、ダクト及び電動機の種別に応じて定まる付録Aに規定する値を用いるか、又は当該住戸において全般換気設備の消費電力P及び全般換気設備の設計風量  stem:[ V_{d} ] を求めて比消費電力 stem:[ f_{SFP} ] を算出する場合には、式(4)により算出し、1/100未満の端数を切り上げた小数第二位までの値とする。なお、付録Aに規定する値を用いる場合であって、異なる種別に該当する換気設備を複数用いる場合においては、各々の比消費電力を比較して最も大きな値を使用することとする。ただし、暖房設備または冷房設備に全般換気機能を有するダクト式セントラル空調機を採用する場合、比消費電力 stem:[ f_{SFP} ] は、付録Aの表A.1における全般換気設備の種類が「ダクト式第一種換気設備（熱交換型換気設備）」の場合の値とする。

[stem]
++++
f_{ SFP } = P \div V_{d}
++++

ここで、

[cols="<.<1,<.<20", frame=none, grid=none, stripes=none]
|===

|stem:[ P ]
|:全般換気設備の消費電力, W

|stem:[ V_{ d } ]
|:全般換気設備の設計風量, m^3^/h

|===

である。

====



<<<
==== 3. 変更内容

====

【メモ：時刻別SFP】

. 計算ロジック（数式中のformula_x）は専門家に任せる
+
恐らく、地域区分、外気温度、空調の稼働状態、局所換気の稼働状態　などが追加で必要になる。

. 分岐条件は、複数の換気方式の組合せが想定されることからプログラム側で考慮する必要がある。
+
例えば、バイパス運転と片側運転の両方を持つ機種を評価する場合など

. 現時点ではプログラムの構成のみを規定する。

. 基本はSFPを時刻別に補正する機能とする。
+
SFP自体を差し替えるのは、複数の換気方式を同時に評価したい場合に問題が発生すると思われる。

====

日付dの時刻tにおける比消費電力 stem:[ f_{SFP, d, t} ] は、換気方式に応じて以下の値となる。 stem:[ f_{SFP} ] は、全般換気設備、ダクト及び電動機の種別に応じて定まる付録Aに規定する値を用いるか、又は当該住戸において全般換気設備の消費電力P及び全般換気設備の設計風量  stem:[ V_{d} ] を求めて比消費電力 stem:[ f_{SFP} ] を算出する場合には、式(4)により算出し、1/100未満の端数を切り上げた小数第二位までの値とする。なお、付録Aに規定する値を用いる場合であって、異なる種別に該当する換気設備を複数用いる場合においては、各々の比消費電力を比較して最も大きな値を使用することとする。ただし、暖房設備または冷房設備に全般換気機能を有するダクト式セントラル空調機を採用する場合、比消費電力 stem:[ f_{SFP} ] は、付録Aの表A.1における全般換気設備の種類が「ダクト式第一種換気設備（熱交換型換気設備）」の場合の値とする。

[stem]
++++
f_{ SFP, d, t } = f_{ SFP } \times C_{ d, t}
++++

[stem]
++++
f_{ SFP } = P \div V_{d}
++++

[stem]
++++
C_{ d, t } = C_{bypass, d, t} \times C_{single, d, t} \times... \times C_{others, d, t}
++++


[stem]
++++
C_{ bypass, d, t } = 
\begin{cases}
formula_1 & ,(\mbox{冷房期} \land 第一種熱交換型) \\
formula_2 & ,(\mbox{暖房期}) \land 第一種熱交換型 \\
formula_3 & ,(\mbox{中間期} \land 第一種熱交換型) \\
1 & ,(\mbox{その他})
\end{cases}
++++

[stem]
++++
C_{ single, d, t } = 
\begin{cases}
formula_1 & ,(\mbox{冷房期} \land 第一種熱交換型)　\\
formula_2 & ,(\mbox{暖房期} \land 第一種熱交換型)　\\
formula_3 & ,(\mbox{中間期} \land 第一種熱交換型 \land 空調運転=OFF) \\
1 & ,(\mbox{その他})
\end{cases}
++++

ここで、

[cols="<.<1,<.<20", frame=none, grid=none, stripes=none]
|===

|stem:[ f_{ SFP, d, t }  ]
|：日付 stem:[ d ] の時刻 stem:[ t ] における比消費電力,W/(m^3^/h)

|stem:[ C_{ d, t }  ]
|：日付 stem:[ d ] の時刻 stem:[ t ] における比消費電力の補正係数,-

|stem:[ C_{ bypass, d, t }  ]
|：日付 stem:[ d ] の時刻 stem:[ t ] におけるバイパス運転比消費電力の補正係数,-

|stem:[ C_{ single, d, t }  ]
|：日付 stem:[ d ] の時刻 stem:[ t ] における片側運転の比消費電力の補正係数,-

|stem:[ f_{ SFP }  ]
|：比消費電力,W/(m^3^/h)

|stem:[ P ]
|:全般換気設備の消費電力, W

|stem:[ V_{ d } ]
|:全般換気設備の設計風量, m^3^/h

|===

である。


==== 4. 備考

なし
